version: '3'

services:
  cdr-analyzer:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DEBUG=False
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    restart: unless-stopped

# Hapus service postgres karena kita menggunakan database Supabase